name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # 打包依賴並構建 Lambda Layer
      - name: Build Lambda Layer
        run: |
          mkdir -p layer/python
          pip install -r requirements.txt -t layer/python
          cd layer
          zip -r ../lambda_layer.zip .

      # 部署 Lambda Layer
      - name: Deploy Lambda Layer
        uses: appleboy/lambda-action@master
        with:
          layer: lambda_layer.zip
          region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 打包 Lambda 函數（僅代碼）
      - name: Package Function Code
        run: |
          zip -r function.zip app.py

      # 部署 Lambda 函數
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          function_name: LineBuddySplit_OpenAi
          region: us-east-1
          zip_file: function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
