name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"  # 與 AWS Lambda Runtime 一致

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip the function
        run: zip -r function.zip .  # 打包程式碼和依賴項

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1.1.1
        with:
          function-name: LineBuddySplit_OpenAi  # 替換為你的 Lambda 函數名稱
          zip-file: function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
